// Regenerate worker/bundle.mjs (build artifact, not committed) — see docs/09.
// Concatenates the protocol-critical modules verbatim (imports/exports stripped
// for single-file module form), embeds the static frontend, and appends the
// Workers glue (worker/glue.mjs). Also emits KV-staging artifacts
// (worker/out/chunk_*.txt + worker/out/staging.json) for the hash-gated upload.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { createHash } from "node:crypto";
import { gzipSync } from "node:zlib";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const impl = join(root, "implementation");

const CHUNK = 2500; // ~2500-char chunks per docs/09 postmortem pattern

// Drop ESM import lines and export keywords so modules concatenate into one file.
function stripModule(src) {
  return src
    .split("\n")
    .filter((l) => !/^import\s/.test(l))
    .filter((l) => !/^export\s*\{[^}]*\};?\s*$/.test(l))
    .join("\n")
    .replace(/^export\s+(?=(async\s+)?(function|class|const|let)\s)/gm, "");
}

const read = (p) => readFileSync(p, "utf8");

const parts = [];
parts.push(`// pdd-monkeytype-ui — Cloudflare Workers bundle (build artifact).
// Generated by worker/build.mjs on ${new Date().toISOString()} — do not edit.
// Protocol-critical modules are verbatim from implementation/src (imports/exports
// stripped); platform glue (KvStore, fetch router) appended from worker/glue.mjs.
import { scryptSync, randomBytes, createHmac, timingSafeEqual, randomUUID } from "node:crypto";
`);

for (const [label, rel] of [
  ["shared/stats.js", "src/shared/stats.js"],
  ["engine/countChars.js", "src/engine/countChars.js"],
  ["engine/words.js", "src/engine/words.js"],
  ["engine/session.js", "src/engine/session.js"],
  ["anticheat/index.js", "src/anticheat/index.js"],
  ["server/validate.js", "src/server/validate.js"],
]) {
  parts.push(`\n// ============ BEGIN verbatim: ${label} ============\n`);
  parts.push(stripModule(read(join(impl, rel))));
  parts.push(`\n// ============ END verbatim: ${label} ============\n`);
}

// auth.js: verbatim except the demo token secret (process.env -> constant).
parts.push(`\n// ============ BEGIN verbatim: server/auth.js (demo secret) ============\n`);
parts.push(
  stripModule(read(join(impl, "src/server/auth.js"))).replace(
    'process.env.PDD_TOKEN_SECRET || "dev-only-insecure-token-secret"',
    '"pdd-demo-token-secret"'
  )
);
parts.push(`\n// ============ END verbatim: server/auth.js ============\n`);

// Static assets: public frontend + isomorphic engine/shared modules served verbatim.
const text = (p, type) => ({ body: read(p), type });
const assets = {
  "/": text(join(impl, "public/index.html"), "text/html; charset=utf-8"),
  "/index.html": text(join(impl, "public/index.html"), "text/html; charset=utf-8"),
  "/style.css": text(join(impl, "public/style.css"), "text/css; charset=utf-8"),
  "/app.js": text(join(impl, "public/app.js"), "text/javascript; charset=utf-8"),
  "/engine/session.js": text(join(impl, "src/engine/session.js"), "text/javascript; charset=utf-8"),
  "/engine/countChars.js": text(join(impl, "src/engine/countChars.js"), "text/javascript; charset=utf-8"),
  "/engine/words.js": text(join(impl, "src/engine/words.js"), "text/javascript; charset=utf-8"),
  "/shared/stats.js": text(join(impl, "src/shared/stats.js"), "text/javascript; charset=utf-8"),
};

const glue = read(join(here, "glue.mjs")).replace(
  "/*__ASSETS__*/ {}",
  JSON.stringify(assets, null, 1)
);
parts.push(glue);

const bundle = parts.join("");
writeFileSync(join(here, "bundle.mjs"), bundle);

// ---- KV-staging artifacts: gzip + base64 + ~2500-char chunks + SHA-256 ----
const gz = gzipSync(Buffer.from(bundle, "utf8"), { level: 9 });
const b64 = gz.toString("base64");
mkdirSync(join(here, "out"), { recursive: true });
const chunks = [];
for (let i = 0; i < b64.length; i += CHUNK) {
  const c = b64.slice(i, i + CHUNK);
  const sha = createHash("sha256").update(c).digest("hex");
  const idx = chunks.length;
  writeFileSync(join(here, "out", `chunk_${idx}.txt`), c);
  chunks.push({ i: idx, len: c.length, sha256: sha, sha16: sha.slice(0, 16) });
}
const staging = {
  script: "pdd-monkeytype-ui",
  bundleBytes: Buffer.byteLength(bundle),
  bundleSha256: createHash("sha256").update(bundle).digest("hex"),
  gzipBytes: gz.length,
  b64len: b64.length,
  chunkSize: CHUNK,
  chunkCount: chunks.length,
  chunks,
};
writeFileSync(join(here, "out", "staging.json"), JSON.stringify(staging, null, 2));
console.log(JSON.stringify({ ...staging, chunks: chunks.map((c) => `${c.i}:${c.len}:${c.sha16}`) }, null, 2));
