// pdd-monkeytype — Cloudflare Workers candidate (v2-workers).
// Same protocol-critical modules as the Node candidate (engine, stats, anticheat,
// validators) — protocol-level substitutability in action. Platform glue (Express
// routes, JSON-file store) is replaced by a fetch router + KV store. RVL file
// ledger is Node-only; this demo runs without it (documented limitation).
import { scryptSync, randomBytes, createHmac, timingSafeEqual, randomUUID } from "node:crypto";

// NOTE: the deployed bundle is generated by concatenating implementation/src modules
// verbatim (shared/stats.js, engine/countChars.js, engine/words.js, engine/session.js,
// anticheat/index.js, server/validate.js) + embedded static assets + the glue below.
// See worker/BUILD.md for regeneration instructions.

export { default } from "./bundle.mjs";
